services:
  - type: web
    name: my-portfolio
    plan: free
    env: node
    buildCommand: pnpm install && pnpm run build
    startCommand: pnpm run start
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 22.x
      - key: PNPM_VERSION
        value: 9.15.4
